export default async function getMovies(): Promise<movie[]> {
    const res: movie[] = [
        {
            ID: "111111111",
            MNAME: "The Shawshank Redemption",
            GENRE: "Drama",
            RELEASEDAT: 1994,
            AGE_RESTRIC: 16,
            MLANGUAGE: "English",
            DIRECTOR: "Frank Darabont",
            PERFORMER: "Tim Robbins, Morgan Freeman, Bob Gunton",
            NATION: "United States",
            MTIME: "02:22:00",
            M_ID: null,
            MDESCRIPTION: "Chronicles the experiences of a formerly successful banker as a prisoner in the gloomy jailhouse of Shawshank after being found guilty of a crime he did not commit. The film portrays the man's unique way of dealing with his new, torturous life; along the way he befriends a number of fellow prisoners, most notably a wise long-term inmate named Red."
        },
        {
            ID: "111111112",
            MNAME: "The Godfather",
            GENRE: "Crime, Drama",
            RELEASEDAT: 1972,
            AGE_RESTRIC: 0,
            MLANGUAGE: "English",
            DIRECTOR: "Francis Ford Coppola",
            PERFORMER: "Morgan Freeman, Bob Gunton, James Caan",
            NATION: "United States",
            MTIME: "02:55:00",
            M_ID: null,
            MDESCRIPTION: "The Godfather \"Don\" Vito Corleone is the head of the Corleone mafia family in New York. He is at the event of his daughter's wedding. Michael, Vito's youngest son and a decorated WW II Marine is also present at the wedding. Michael seems to be uninterested in being a part of the family business. Vito is a powerful man, and is kind to all those who give him respect but is ruthless against those who do not. But when a powerful and treacherous rival wants to sell drugs and needs the Don's influence for the same, Vito refuses to do it. What follows is a clash between Vito's fading old values and the new ways which may cause Michael to do the thing he was most reluctant in doing and wage a mob war against all the other mafia families which could tear the Corleone family apart."
        },
        {
            ID: "111111113",
            MNAME: "The Dark Knight",
            GENRE: "Action, Crime, Drama, Thriller",
            RELEASEDAT: 2008,
            AGE_RESTRIC: 13,
            MLANGUAGE: "English",
            DIRECTOR: "Christopher Nolan",
            PERFORMER: "Christian Bale, Heath Ledger, Aaron Eckhart",
            NATION: "United States, United Kingdom",
            MTIME: "02:32:00",
            M_ID: null,
            MDESCRIPTION: "Set within a year after the events of Batman Begins (2005), Batman, Lieutenant James Gordon, and new District Attorney Harvey Dent successfully begin to round up the criminals that plague Gotham City, until a mysterious and sadistic criminal mastermind known only as \"The Joker\" appears in Gotham, creating a new wave of chaos. Batman's struggle against The Joker becomes deeply personal, forcing him to \"confront everything he believes\" and improve his technology to stop him. A love triangle develops between Bruce Wayne, Dent, and Rachel Dawes."
        },
        {
            ID: "111111114",
            MNAME: "The Godfather 2",
            GENRE: "Crime, Drama",
            RELEASEDAT: 1974,
            AGE_RESTRIC: 0,
            MLANGUAGE: "English",
            DIRECTOR: "Francis Ford Coppola",
            PERFORMER: "Al Pacino, Robert De Niro, Robert Duvall",
            NATION: "United States",
            MTIME: "02:22:00",
            M_ID: "111111111",
            MDESCRIPTION: "The continuing saga of the Corleone crime family tells the story of a young Vito Corleone growing up in Sicily and in 1910s New York; and follows Michael Corleone in the 1950s as he attempts to expand the family business into Las Vegas, Hollywood and Cuba."
        },
        {
            ID: "111111115",
            MNAME: "12 Angry Men",
            GENRE: "Crime, Drama",
            RELEASEDAT: 1957,
            AGE_RESTRIC: 0,
            MLANGUAGE: "English",
            DIRECTOR: "Sidney Lumet",
            PERFORMER: "Henry Fonda, Lee J.Cobb, Martin Balsam",
            NATION: "United States",
            MTIME: "01:36:00",
            M_ID: null,
            MDESCRIPTION: "The defense and the prosecution have rested, and the jury is filing into the jury room to decide if a young man is guilty or innocent of murdering his father. What begins as an open-and-shut case of murder soon becomes a detective story that presents a succession of clues creating doubt, and a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, AND each other. Based on the play, all of the action takes place on the stage of the jury room."
        },
        {
            ID: "111111116",
            MNAME: "Schindler's List",
            GENRE: "Biography, Drama, History",
            RELEASEDAT: 1993,
            AGE_RESTRIC: 16,
            MLANGUAGE: "English",
            DIRECTOR: "Steven Speilberg",
            PERFORMER: "Liam Neeson, Ralph Fiennes, Ben Kingsley",
            NATION: "United States",
            MTIME: "03:15:00",
            M_ID: null,
            MDESCRIPTION: "Oskar Schindler is a vain and greedy German businessman who becomes an unlikely humanitarian amid the barbaric German Nazi reign when he feels compelled to turn his factory into a refuge for Jews. Based on the true story of Oskar Schindler who managed to save about 1100 Jews from being gassed at the Auschwitz concentration camp, it is a testament to the good in all of us."
        },
        {
            ID: "111111117",
            MNAME: "The Lord of the Rings: The Return of the King",
            GENRE: "Action, Adventure, Drama",
            RELEASEDAT: 2003,
            AGE_RESTRIC: 13,
            MLANGUAGE: "English",
            DIRECTOR: "Peter Jackson",
            PERFORMER: "Elijah Wood, Viggo Mortensen, Ian McKellen",
            NATION: "New Zealand",
            MTIME: "03:21:00",
            M_ID: "111111124",
            MDESCRIPTION: "The final confrontation between the forces of good and evil fighting for control of the future of Middle-earth. Frodo and Sam reach Mordor in their quest to destroy the One Ring, while Aragorn leads the forces of good against Sauron's evil army at the stone city of Minas Tirith."
        },
        {
            ID: "111111118",
            MNAME: "Pulp Fiction",
            GENRE: "Crime, Drama",
            RELEASEDAT: 1994,
            AGE_RESTRIC: 18,
            MLANGUAGE: "English",
            DIRECTOR: "Quentin Tarantino",
            PERFORMER: "John Travolta, Uma Thurman, Samuel L. Jackson",
            NATION: "United States",
            MTIME: "02:34:00",
            M_ID: null,
            MDESCRIPTION: "Jules Winnfield (Samuel L. Jackson) and Vincent Vega (John Travolta) are two hit men who are out to retrieve a suitcase stolen from their employer, mob boss Marsellus Wallace (Ving Rhames). Wallace has also asked Vincent to take his wife Mia (Uma Thurman) out a few days later when Wallace himself will be out of town. Butch Coolidge (Bruce Willis) is an aging boxer who is paid by Wallace to lose his fight. The lives of these seemingly unrelated people are woven together comprising of a series of funny, bizarre and uncalled-for incidents."
        },
        {
            ID: "111111119",
            MNAME: "The Lord of the Rings: The Fellowship of the Ring",
            GENRE: "Action, Adventure, Drama",
            RELEASEDAT: 2001,
            AGE_RESTRIC: 13,
            MLANGUAGE: "English, Sindarin",
            DIRECTOR: "Peter Jackson",
            PERFORMER: "Elijah Wood, Orlando Bloom, Ian McKellen",
            NATION: "United States, New Zealand",
            MTIME: "02:58:00",
            M_ID: null,
            MDESCRIPTION: "An ancient Ring thought lost for centuries has been found, and through a strange twist of fate has been given to a small Hobbit named Frodo. When Gandalf discovers the Ring is in fact the One Ring of the Dark Lord Sauron, Frodo must make an epic quest to the Cracks of Doom in order to destroy it. However, he does not go alone. He is joined by Gandalf, Legolas the elf, Gimli the Dwarf, Aragorn, Boromir, and his three Hobbit friends Merry, Pippin, and Samwise. Through mountains, snow, darkness, forests, rivers and plains, facing evil and danger at every corner the Fellowship of the Ring must go. Their quest to destroy the One Ring is the only hope for the end of the Dark Lords reign."
        },
        {
            ID: "111111120",
            MNAME: "The Good, the Bad and the Ugly",
            GENRE: "Adventure, Western",
            RELEASEDAT: 1966,
            AGE_RESTRIC: 0,
            MLANGUAGE: "Italian",
            DIRECTOR: "Sergio Leone",
            PERFORMER: "Clint Eastwood, Eli Wallach, Lee Van Cleef",
            NATION: "Italy, Spain, West Germany",
            MTIME: "02:58:00",
            M_ID: null,
            MDESCRIPTION: "During the American Civil War, three men set off to find $200,000.00 in buried gold coins. Tuco and Blondie have known each other"
        },
        {
            ID: "111111121",
            MNAME: "Forrest Gump",
            GENRE: "Drama, Romance",
            RELEASEDAT: 1994,
            AGE_RESTRIC: 13,
            MLANGUAGE: "English",
            DIRECTOR: "Robert Zemeckis",
            PERFORMER: "Tom Hanks, Robin Wright, Gary Sinise",
            NATION: "United States",
            MTIME: "02:22:00",
            M_ID: null,
            MDESCRIPTION: "Forrest Gump is a simple man with a low I.Q. but good intentions. He is running through childhood with his best and only friend Jenny. His 'mama' teaches him the ways of life and leaves him to choose his destiny. Forrest joins the army for service in Vietnam, finding new friends called Dan and Bubba, he wins medals, creates a famous shrimp fishing fleet, inspires people to jog, starts a ping-pong craze, creates the smiley, writes bumper stickers and songs, donates to people and meets the president several times. However, this is all irrelevant to Forrest who can only think of his childhood sweetheart Jenny Curran, who has messed up her life. Although in the end all he wants to prove is that anyone can love anyone."
        },
        {
            ID: "111111122",
            MNAME: "Fight Club",
            GENRE: "Drama",
            RELEASEDAT: 1999,
            AGE_RESTRIC: 18,
            MLANGUAGE: "English",
            DIRECTOR: "David Fincher",
            PERFORMER: "Brad Pitt, Edward Norton, Meat Loaf",
            NATION: "Germany, United States",
            MTIME: "02:19:00",
            M_ID: null,
            MDESCRIPTION: "A nameless first person narrator (Edward Norton) attends support groups in attempt to subdue his emotional state and relieve his insomniac state. When he meets Marla (Helena Bonham Carter), another fake attendee of support groups, his life seems to become a little more bearable. However when he associates himself with Tyler (Brad Pitt) he is dragged into an underground fight club and soap making scheme. Together the two men spiral out of control and engage in competitive rivalry for love and power."
        },
        {
            ID: "111111123",
            MNAME: "The Lord of the Rings: The Two Towers",
            GENRE: "Action, Adventure, Drama",
            RELEASEDAT: 2002,
            AGE_RESTRIC: 13,
            MLANGUAGE: "English, Sindarin, Old English",
            DIRECTOR: "Peter Jackson",
            PERFORMER: "Elijah Wood, Ian McKellen, Viggo Mortensen",
            NATION: "New Zealand, United States",
            MTIME: "02:58:00",
            M_ID: "111111119",
            MDESCRIPTION: "The continuing quest of Frodo and the Fellowship to destroy the One Ring. Frodo and Sam discover they are being followed by the mysterious Gollum. Aragorn, the Elf archer Legolas, and Gimli the Dwarf encounter the besieged Rohan kingdom, whose once great King Theoden has fallen under Saruman's deadly spell."
        },
        {
            ID: "111111124",
            MNAME: "Inception",
            GENRE: "Action, Adventure, Sci-Fi",
            RELEASEDAT: 2010,
            AGE_RESTRIC: 13,
            MLANGUAGE: "English, Japanese, French",
            DIRECTOR: "Christopher Nolan",
            PERFORMER: "Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page",
            NATION: "United States, United Kingdom",
            MTIME: "02:28:00",
            M_ID: null,
            MDESCRIPTION: "Dom Cobb is a skilled thief, the absolute best in the dangerous art of extraction, stealing valuable secrets from deep within the subconscious during the dream state, when the mind is at its most vulnerable. Cobb's rare ability has made him a coveted player in this treacherous new world of corporate espionage, but it has also made him an international fugitive and cost him everything he has ever loved. Now Cobb is being offered a chance at redemption. One last job could give him his life back but only if he can accomplish the impossible, inception. Instead of the perfect heist, Cobb and his team of specialists have to pull off the reverse: their task is not to steal an idea, but to plant one. If they succeed, it could be the perfect crime. But no amount of careful planning or expertise can prepare the team for the dangerous enemy that seems to predict their every move. An enemy that only Cobb could have seen coming."
        },
        {
            ID: "111111125",
            MNAME: "Star Wars: Episode V - The Empire Strikes Back",
            GENRE: "Action, Adventure, Fantasy",
            RELEASEDAT: 1980,
            AGE_RESTRIC: 0,
            MLANGUAGE: "English",
            DIRECTOR: "Irvin Kershner",
            PERFORMER: "Mark Hamill, Harrison Ford, Carrie Fisher",
            NATION: "United States",
            MTIME: "02:04:00",
            M_ID: null,
            MDESCRIPTION: "The legendary saga continues as the Rebel Alliance faces increasing challenges from the powerful Galactic Empire. Luke Skywalker, Han Solo, and Princess Leia Organa find themselves confronting new trials that test their courage, friendships, and beliefs. The Rebel Alliance has established a hidden base on the icy planet of Hoth, where they hope to regroup and plan their next moves against the Empire. Luke Skywalker receives a message from a familiar source, prompting him to seek further guidance in understanding his connection to the Force. Han Solo and Princess Leia's journey takes them on a perilous path as they navigate through a galaxy under Imperial control. Their actions and decisions lead to unforeseen consequences that will impact the fate of the Rebellion. Meanwhile, the dark presence of Darth Vader looms, as he relentlessly pursues the Rebels while dealing with inner conflicts of his own."
        },
        {
            ID: "111111126",
            MNAME: "The Matrix",
            GENRE: "Action, Sci-Fi",
            RELEASEDAT: 1999,
            AGE_RESTRIC: 0,
            MLANGUAGE: "English",
            DIRECTOR: "Lana Wachowski, Lilly Wachowski",
            PERFORMER: "Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss",
            NATION: "United States, Australia",
            MTIME: "02:16:00",
            M_ID: null,
            MDESCRIPTION: "Thomas A. Anderson is a man living two lives. By day he is an average computer programmer and by night a hacker known as Neo. Neo has always questioned his reality, but the truth is far beyond his imagination. Neo finds himself targeted by the police when he is contacted by Morpheus, a legendary computer hacker branded a terrorist by the government. As a rebel against the machines, Neo must confront the agents: super-powerful computer programs devoted to stopping Neo and the entire human rebellion."
        },
        {
            ID: "111111127",
            MNAME: "Goodfellas",
            GENRE: "Biography, Drama, Crime",
            RELEASEDAT: 1990,
            AGE_RESTRIC: 13,
            MLANGUAGE: "English, Italian",
            DIRECTOR: "Martin Scorsese",
            PERFORMER: "Robert De Niro, Ray Liotta, Joe Pesci",
            NATION: "United States",
            MTIME: "02:25:00",
            M_ID: null,
            MDESCRIPTION: "Henry Hill might be a small time gangster, who may have taken part in a robbery with Jimmy Conway and Tommy De Vito, two other gangsters who might have set their sights a bit higher. His two partners could kill off everyone else involved in the robbery, and slowly start to think about climbing up through the hierarchy of the Mob. Henry, however, might be badly affected by his partners' success, but will he consider stooping low enough to bring about the downfall of Jimmy and Tommy?"
        },
        {
            ID: "111111128",
            MNAME: "One Flew Over the Cuckoo's Nest",
            GENRE: "Drama",
            RELEASEDAT: 1975,
            AGE_RESTRIC: 16,
            MLANGUAGE: "English",
            DIRECTOR: "Milos Forman",
            PERFORMER: "Jack Nicholson, Louise Fletcher, Michael Berryman",
            NATION: "United States",
            MTIME: "02:13:00",
            M_ID: null,
            MDESCRIPTION: "McMurphy has a criminal past and has once again gotten himself into trouble and is sentenced by the court. To escape labor duties in prison, McMurphy pleads insanity and is sent to a ward for the mentally unstable. Once here, McMurphy both endures and stands witness to the abuse and degradation of the oppressive Nurse Ratched, who gains superiority and power through the flaws of the other inmates. McMurphy and the other inmates band together to make a rebellious stance against the atrocious Nurse."
        },
        {
            ID: "111111129",
            MNAME: "Se7en",
            GENRE: "Crime, Drama, Mystery",
            RELEASEDAT: 1995,
            AGE_RESTRIC: 16,
            MLANGUAGE: "English",
            DIRECTOR: "David Fincher",
            PERFORMER: "Morgan Freeman, Brad Pitt, Kevin Spacey",
            NATION: "United States",
            MTIME: "02:07:00",
            M_ID: null,
            MDESCRIPTION: "A film about two homicide detectives' (Morgan Freeman and Brad Pitt) desperate hunt for a serial killer who justifies his crimes as absolution for the world's ignorance of the Seven Deadly Sins. The movie takes us from the tortured remains of one victim to the next as the sociopathic \"John Doe\" (Kevin Spacey) sermonizes to Detectives Somerset and Mills -- one sin at a time. The sin of Gluttony comes first and the murderer's terrible capacity is graphically demonstrated in the dark and subdued tones characteristic of film noir. The seasoned and cultured but jaded Somerset researches the Seven Deadly Sins in an effort to understand the killer's modus operandi while the bright but green and impulsive Detective Mills (Pitt) scoffs at his efforts to get inside the mind of a killer..."
        },
        {
            ID: "111111130",
            MNAME: "It's a Wonderful Life",
            GENRE: "Drama, Family, Fantasy, Romance",
            RELEASEDAT: 1946,
            AGE_RESTRIC: 13,
            MLANGUAGE: "English, French",
            DIRECTOR: "Frank Capra",
            PERFORMER: "James Stewart, Donna Reed, Lionel Barrymore",
            NATION: "United States",
            MTIME: "02:10:00",
            M_ID: null,
            MDESCRIPTION: "George Bailey has spent his entire life giving of himself to the people of Bedford Falls. He has always longed to travel but never had the opportunity in order to prevent rich skinflint Mr. Potter from taking over the entire town. All that prevents him from doing so is George's modest building and loan company, which was founded by his generous father. But on Christmas Eve, George's Uncle Billy loses the business's $8,000 while intending to deposit it in the bank. Mr. Potter finds the misplaced money and hides it from Uncle Billy. When the bank examiner discovers the shortage later that night, George realizes that he will be held responsible and sent to jail and the company will collapse, finally allowing Mr. Potter to take over the town. Thinking of his wife, Mary, their four children, and others he loves will be better off with him dead, he contemplates suicide. But the prayers of his loved ones result in his guardian angel named Clarence Odbody coming to Earth to help him, with the promise of earning his wings. He shows him what things would have been like if he had never been born."
        }
    ]
    return res
}
